### ISSUE TITLE
Unable to reinstall when specified actions are set

### ISSUE THREAD

**Issue by quexpl** [smpallen99/coherence#139]
In my project i have disabled delete action in registerable, so my config look like this:
```
  opts: [
    ....
    registerable: [:show, :new, :create, :edit, :update]
  ],
```

when i run ```mix coherence.install --reinstall``` it throws error:

```
** (ArgumentError) argument error
    :erlang.atom_to_binary({:registerable, [:show, :new, :create, :edit, :update]}, :utf8)
    lib/mix/tasks/coherence.install.ex:899: Mix.Tasks.Coherence.Install.config_option/2
    (elixir) lib/enum.ex:1623: Enum."-reduce/3-lists^foldl/2-0-"/3
    lib/mix/tasks/coherence.install.ex:167: Mix.Tasks.Coherence.Install.do_run/1
    (mix) lib/mix/task.ex:296: Mix.Task.run_task/3
    (mix) lib/mix/cli.ex:58: Mix.CLI.run_task/2
    (elixir) lib/code.ex:363: Code.require_file/2
```

There is no problem when is no specific actions, and coherence uses default settings.

**Comment by smpallen99** [comment]
good catch. I don't think I've ever tested this.

**Comment by pdgonzalez872** [comment]
@quexpl is this issue still relevant? If not, could you please close it? Thanks!
