### ISSUE TITLE
Coherence Routing to Custom SessionController unexpectedly

### ISSUE THREAD

**Issue by cdesch** [smpallen99/coherence#180]
I'm using guardian for the API and Coherence with ExAdmin. The design is for Coherence to handle any browser authentication and Guardian to handle any API authentication. They should separately coexist within their own bounds, although they seem to be bleeding over. The API which has its own pipeline, and namespace of `/api` has its own `SessionController`. 

When Logging into ExAdmin via Coherence --> Coherence is trying to use the `SessionController` from the API, resulting in this error message as it should:

```
FunctionClauseError at POST /api/sessions
no function clause matching in MyRewardsWeb.SessionController.authenticate/1
```

Full Message: 
```

[debug] Processing by MyRewardsWeb.SessionController.create/2
  Parameters: %{"_csrf_token" => "ZEoiKBQuEUkvHVkcLHgQIQw7JDN3AAAA7+LbpFe/cj7Wi5wWehFg0w==", "_utf8" => "✓", "session" => %{"email" => "admin@example.com", "password" => "[FILTERED]"}}
  Pipelines: [:api]
[info] Sent 500 in 69ms
[error] #PID<0.642.0> running MyRewardsWeb.Endpoint terminated
Server: localhost:4000 (http)
Request: POST /api/sessions
** (exit) an exception was raised:
    ** (FunctionClauseError) no function clause matching in MyRewardsWeb.SessionController.authenticate/1
        (my_rewards_web) web/controllers/session_controller.ex:55: MyRewardsWeb.SessionController.authenticate(%{"_csrf_token" => "ZEoiKBQuEUkvHVkcLHgQIQw7JDN3AAAA7+LbpFe/cj7Wi5wWehFg0w==", "_utf8" => "✓", "session" => %{"email" => "admin@example.com", "password" => "password"}})
        (my_rewards_web) web/controllers/session_controller.ex:8: MyRewardsWeb.SessionController.create/2
        (my_rewards_web) web/controllers/session_controller.ex:1: MyRewardsWeb.SessionController.action/2
        (my_rewards_web) web/controllers/session_controller.ex:1: MyRewardsWeb.SessionController.phoenix_controller_pipeline/2
        (my_rewards_web) lib/my_rewards_web/endpoint.ex:1: MyRewardsWeb.Endpoint.instrument/4
        (my_rewards_web) lib/phoenix/router.ex:261: MyRewardsWeb.Router.dispatch/2
        (my_rewards_web) web/router.ex:1: MyRewardsWeb.Router.do_call/2
        (my_rewards_web) lib/my_rewards_web/endpoint.ex:1: MyRewardsWeb.Endpoint.phoenix_pipeline/1
        (my_rewards_web) lib/plug/debugger.ex:123: MyRewardsWeb.Endpoint."call (overridable 3)"/2
        (my_rewards_web) lib/my_rewards_web/endpoint.ex:1: MyRewardsWeb.Endpoint.call/2
        (plug) lib/plug/adapters/cowboy/handler.ex:15: Plug.Adapters.Cowboy.Handler.upgrade/4
        (cowboy) /Users/cj/elixir_projects/my_rewards_platform/deps/cowboy/src/cowboy_protocol.erl:442: :cowboy_protocol.execute/4
```

My router setup: 

```
defmodule MyRewardsWeb.Router do
  use MyRewardsWeb.Web, :router
  use Coherence.Router
  use ExAdmin.Router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Coherence.Authentication.Session
  end

  pipeline :protected do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Coherence.Authentication.Session, protected: true
  end

  pipeline :api do
    plug :accepts, ["json"]
    plug Guardian.Plug.VerifyHeader, realm: "Bearer"
    plug Guardian.Plug.LoadResource
  end

  scope "/" do
    pipe_through :browser
    coherence_routes
  end

  scope "/" do
    pipe_through :protected
    coherence_routes :protected
  end

  scope "/", MyRewardsWeb do
    pipe_through :browser # Use the default browser stack
    get "/", PageController, :index
    get "/terms", PageController, :terms
    get "/privacy", PageController, :privacy
  end

  scope "/admin", ExAdmin do
    pipe_through :protected
    admin_routes
  end

  scope "/api", MyRewardsWeb, as: :api do
    pipe_through :api

    post "/sessions", SessionController, :create
    delete "/sessions", SessionController, :delete
    post "/sessions/refresh", SessionController, :refresh
    resources "/merchants", MerchantController,  except:  [:new, :edit, :delete] do
      get "/users", Merchant.UserController, :index
      get "/balance/:user_id", Merchant.UserController, :balance
      get "/transactions", Merchant.TransactionController, :index
    end
    resources "/categories", CategoryController, only:  [:index]
    resources "/transactions", TransactionController, except: [:new, :edit]
    resources "/status", StatusController, only: [:index]
    resources "/users", UserController, except:  [:new, :edit, :delete] do
      get "/merchants", User.MerchantController, :index
      get "/merchant", User.MerchantController, :merchant
      get "/transactions", User.TransactionController, :index
      get "/rewards", User.RewardController, :index
    end

    post "/users/verify_sms", UserController, :verify_sms
    post "/users/validate_phone",  UserController, :validate_phone
    post "/merchants/user", MerchantController, :user
    resources "/rewards", RewardController
 end
end
```

which results in these routes:

```
cjs-MBP15:my_rewards_web cj$ mix phoenix.routes
                 session_path  GET     /sessions/new                                            Coherence.SessionController :new
                 session_path  POST    /sessions                                                Coherence.SessionController :create
            registration_path  GET     /registrations/new                                       Coherence.RegistrationController :new
            registration_path  POST    /registrations                                           Coherence.RegistrationController :create
                password_path  GET     /passwords/new                                           Coherence.PasswordController :new
                password_path  POST    /passwords                                               Coherence.PasswordController :create
                password_path  GET     /passwords/:id/edit                                      Coherence.PasswordController :edit
                password_path  PATCH   /passwords/:id                                           Coherence.PasswordController :update
                               PUT     /passwords/:id                                           Coherence.PasswordController :update
                  unlock_path  GET     /unlocks/new                                             Coherence.UnlockController :new
                  unlock_path  POST    /unlocks                                                 Coherence.UnlockController :create
                  unlock_path  GET     /unlocks/:id/edit                                        Coherence.UnlockController :edit
                 session_path  DELETE  /sessions                                                Coherence.SessionController :delete
            registration_path  GET     /registrations                                           Coherence.RegistrationController :show
            registration_path  PUT     /registrations                                           Coherence.RegistrationController :update
            registration_path  PATCH   /registrations                                           Coherence.RegistrationController :update
            registration_path  GET     /registrations/edit                                      Coherence.RegistrationController :edit
            registration_path  DELETE  /registrations                                           Coherence.RegistrationController :delete
                    page_path  GET     /                                                        MyRewardsWeb.PageController :index
                    page_path  GET     /terms                                                   MyRewardsWeb.PageController :terms
                    page_path  GET     /privacy                                                 MyRewardsWeb.PageController :privacy
                   admin_path  GET     /admin                                                   ExAdmin.AdminController :dashboard
                   admin_path  GET     /admin/dashboard                                         ExAdmin.AdminController :dashboard
                   admin_path  GET     /admin/page/:page                                        ExAdmin.AdminController :page
                   admin_path  GET     /admin/select_theme/:id                                  ExAdmin.AdminController :select_theme
          admin_resource_path  GET     /admin/:resource                                         ExAdmin.AdminResourceController :index
          admin_resource_path  GET     /admin/:resource/new                                     ExAdmin.AdminResourceController :new
          admin_resource_path  GET     /admin/:resource/csv                                     ExAdmin.AdminResourceController :csv
          admin_resource_path  GET     /admin/:resource/:id                                     ExAdmin.AdminResourceController :show
          admin_resource_path  GET     /admin/:resource/:id/edit                                ExAdmin.AdminResourceController :edit
          admin_resource_path  POST    /admin/:resource                                         ExAdmin.AdminResourceController :create
          admin_resource_path  PATCH   /admin/:resource/:id                                     ExAdmin.AdminResourceController :update
          admin_resource_path  PUT     /admin/:resource/:id                                     ExAdmin.AdminResourceController :update
          admin_resource_path  PUT     /admin/:resource/:id/toggle_attr                         ExAdmin.AdminResourceController :toggle_attr
          admin_resource_path  DELETE  /admin/:resource/:id                                     ExAdmin.AdminResourceController :destroy
          admin_resource_path  POST    /admin/:resource/batch_action                            ExAdmin.AdminResourceController :batch_action
          admin_resource_path  PUT     /admin/:resource/:id/member/:action                      ExAdmin.AdminResourceController :member
          admin_resource_path  PATCH   /admin/:resource/:id/member/:action                      ExAdmin.AdminResourceController :member
          admin_resource_path  GET     /admin/:resource/collection/:action                      ExAdmin.AdminResourceController :collection
       admin_association_path  POST    /admin/:resource/:id/:association_name/update_positions  ExAdmin.AdminAssociationController :update_positions
       admin_association_path  POST    /admin/:resource/:id/:association_name                   ExAdmin.AdminAssociationController :add
       admin_association_path  GET     /admin/:resource/:id/:association_name                   ExAdmin.AdminAssociationController :index
             api_session_path  POST    /api/sessions                                            MyRewardsWeb.SessionController :create
             api_session_path  DELETE  /api/sessions                                            MyRewardsWeb.SessionController :delete
             api_session_path  POST    /api/sessions/refresh                                    MyRewardsWeb.SessionController :refresh
            api_merchant_path  GET     /api/merchants                                           MyRewardsWeb.MerchantController :index
            api_merchant_path  GET     /api/merchants/:id                                       MyRewardsWeb.MerchantController :show
            api_merchant_path  POST    /api/merchants                                           MyRewardsWeb.MerchantController :create
            api_merchant_path  PATCH   /api/merchants/:id                                       MyRewardsWeb.MerchantController :update
                               PUT     /api/merchants/:id                                       MyRewardsWeb.MerchantController :update
       api_merchant_user_path  GET     /api/merchants/:merchant_id/users                        MyRewardsWeb.Merchant.UserController :index
       api_merchant_user_path  GET     /api/merchants/:merchant_id/balance/:user_id             MyRewardsWeb.Merchant.UserController :balance
api_merchant_transaction_path  GET     /api/merchants/:merchant_id/transactions                 MyRewardsWeb.Merchant.TransactionController :index
            api_category_path  GET     /api/categories                                          MyRewardsWeb.CategoryController :index
         api_transaction_path  GET     /api/transactions                                        MyRewardsWeb.TransactionController :index
         api_transaction_path  GET     /api/transactions/:id                                    MyRewardsWeb.TransactionController :show
         api_transaction_path  POST    /api/transactions                                        MyRewardsWeb.TransactionController :create
         api_transaction_path  PATCH   /api/transactions/:id                                    MyRewardsWeb.TransactionController :update
                               PUT     /api/transactions/:id                                    MyRewardsWeb.TransactionController :update
         api_transaction_path  DELETE  /api/transactions/:id                                    MyRewardsWeb.TransactionController :delete
              api_status_path  GET     /api/status                                              MyRewardsWeb.StatusController :index
                api_user_path  GET     /api/users                                               MyRewardsWeb.UserController :index
                api_user_path  GET     /api/users/:id                                           MyRewardsWeb.UserController :show
                api_user_path  POST    /api/users                                               MyRewardsWeb.UserController :create
                api_user_path  PATCH   /api/users/:id                                           MyRewardsWeb.UserController :update
                               PUT     /api/users/:id                                           MyRewardsWeb.UserController :update
       api_user_merchant_path  GET     /api/users/:user_id/merchants                            MyRewardsWeb.User.MerchantController :index
       api_user_merchant_path  GET     /api/users/:user_id/merchant                             MyRewardsWeb.User.MerchantController :merchant
    api_user_transaction_path  GET     /api/users/:user_id/transactions                         MyRewardsWeb.User.TransactionController :index
         api_user_reward_path  GET     /api/users/:user_id/rewards                              MyRewardsWeb.User.RewardController :index
                api_user_path  POST    /api/users/verify_sms                                    MyRewardsWeb.UserController :verify_sms
                api_user_path  POST    /api/users/validate_phone                                MyRewardsWeb.UserController :validate_phone
            api_merchant_path  POST    /api/merchants/user                                      MyRewardsWeb.MerchantController :user
              api_reward_path  GET     /api/rewards                                             MyRewardsWeb.RewardController :index
              api_reward_path  GET     /api/rewards/:id/edit                                    MyRewardsWeb.RewardController :edit
              api_reward_path  GET     /api/rewards/new                                         MyRewardsWeb.RewardController :new
              api_reward_path  GET     /api/rewards/:id                                         MyRewardsWeb.RewardController :show
              api_reward_path  POST    /api/rewards                                             MyRewardsWeb.RewardController :create
              api_reward_path  PATCH   /api/rewards/:id                                         MyRewardsWeb.RewardController :update
                               PUT     /api/rewards/:id                                         MyRewardsWeb.RewardController :update
              api_reward_path  DELETE  /api/rewards/:id                                         MyRewardsWeb.RewardController :delete
```

When logging using the `localhost:4000/admin`, the Coherence Login screen is prompted as it should but when it is submitted it using the `api_session_path` helper which takes it to the `SessionController` instead of the `session_path` helper for Coherence `SessionController`

I'm not sure where I went wrong here. I think it is the routing table but It looks fine. Any help would be appreciated.

**Comment by smpallen99** [comment]
The problems is that your posting to `/api/sessions` and that's why its picking up the api controller. 

In your `defimpl ExAdmin.Authentication` definition, there should be a like like
`def session_path(conn, action), do: Helpers.session_path(conn, action)`

This may be the culprit. Make sure that it resolves to the `/sessions` path.

Let me know if that helps fix the issue.

**Comment by cdesch** [comment]
@smpallen99 Thanks for the direction but the issue persists. No change in error. 

I added a file with `authentication.ex` into `lib/my_rewards_web` as this:

```
defimpl ExAdmin.Authentication, for: Plug.Conn do
  alias MyRewardsWeb.Router.Helpers
  alias MyRewardsWeb.Authentication, as: Auth

  def use_authentication?(_), do: true
  def current_user(conn), do: Auth.current_user(conn)
  def current_user_name(conn), do: Auth.current_user(conn).name
  def session_path(conn, action), do: Helpers.session_path(conn, action)
end

defmodule MyRewardsWeb.Authentication do
  def current_user(conn) do
    Coherence.current_user(conn)
  end
end
```

I think you're right that it is on the ExAdmin side though. Looking at the `session_path` side it looks fine in the console:

```
cjs-MBP15:my_rewards_web cj$ iex -S mix phoenix.server
Erlang/OTP 19 [erts-8.2.2] [source] [64-bit] [smp:8:8] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

[info] Running MyRewardsWeb.Endpoint with Cowboy using http://localhost:4000
Interactive Elixir (1.4.2) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> 08 Apr 15:10:46 - info: compiled 11 files into 7 files, copied 22 in 1.7 sec
iex(2)> import MyRewardsWeb.Router.Helpers
MyRewardsWeb.Router.Helpers
iex(3)> alias MyRewardsWeb.Endpoint
MyRewardsWeb.Endpoint
iex(4)> session_path(Endpoint, :create)
"/sessions"
iex(5)> session_path(Endpoint, :new)   
"/sessions/new"
iex(6)> 
```


I also created a test for creating a new coherence session via the `session_path` helper that passes based on [these tests](https://github.com/smpallen99/coherence/blob/master/test/controllers/session_controller_test.exs)

 ```
 test "coherence create session" do
    password = "password"
    user = MyRewards.register_user!(params_for(:user, password: password))
    conn = build_conn()
    conn = assign conn, :current_user, user
    params = %{"session" => %{"email" => user.email, "password" => "password"}}
    conn = post conn, session_path(conn, :create), params
    assert html_response(conn, 302)
  end
```

**Comment by smpallen99** [comment]
What's the path when you inspect the login form?  Also, can you post ur Coherence config entry. Thanks

**Comment by cdesch** [comment]
The login form submit button doesn't have anything for the path in the raw HTML

```
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Hello Admin1!</title>
    <link rel="stylesheet" href="/css/app.css">
  </head>

  <body>
    <div class="container">
      <header class="header">
        <nav role="navigation">
        </nav>
        <span class="logo"></span>
      </header>

      <p class="alert alert-info" role="alert"></p>
      <p class="alert alert-danger" role="alert"></p>

      <main role="main">
<br \>

<form accept-charset="UTF-8" action="/api/sessions" method="post"><input name="_csrf_token" type="hidden" value="YAg2E1MGTSohRiQJM38gTjprCiYDJgAA3iXY7n9Lm1JBv2G8S8hrDQ=="><input name="_utf8" type="hidden" value="✓">
  <div class="form-group">
<label class="control-label" for="session_email">Email
<abbr class="required" title="required">*</abbr></label>    <input class="form-control" id="session_email" name="session[email]" required="" type="text">
  </div>

  <div class="form-group">
<label class="control-label" for="session_password">Password
<abbr class="required" title="required">*</abbr></label>    <input class="form-control" id="session_password" name="session[password]" required="" type="password">
  </div>


  <div class="form-group">
<button class="btn btn-primary" type="submit">Sign In</button>    <a class="btn" href="/">Cancel</a>
  </div>

  <div class="form-group">
<a href="/passwords/new">Forgot your password?</a>&nbsp; | &nbsp;<a href="/registrations/new">Need An Account?</a>  </div>

</form>      </main>

    </div> <!-- /container -->
    <script src="/js/app.js"></script>
  <iframe src="/phoenix/live_reload/frame" style="display: none;"></iframe>
</body>
</html>

```


Here is the `config.exs`:

```
use Mix.Config

# General application configuration
config :my_rewards_web,
  ecto_repos: [MyRewards.Repo]

# Configures the endpoint
config :my_rewards_web, MyRewardsWeb.Endpoint,
  url: [host: "localhost"],
  secret_key_base: "<REMOVED>",
  render_errors: [view: MyRewardsWeb.ErrorView, accepts: ~w(html json)],
  pubsub: [name: MyRewardsWeb.PubSub,
           adapter: Phoenix.PubSub.PG2]

# Configures Elixir's Logger
config :logger, :console,
  format: "$time $metadata[$level] $message\n",
  metadata: [:request_id]


config :ex_admin,
  repo: MyRewards.Repo,
  module: MyRewardsWeb,
  modules: [
    MyRewardsWeb.ExAdmin.Dashboard,
    MyRewardsWeb.ExAdmin.Category,
    MyRewardsWeb.ExAdmin.User,
    MyRewardsWeb.ExAdmin.Transaction,
    MyRewardsWeb.ExAdmin.Merchant,
    MyRewardsWeb.ExAdmin.Reward,
  ],
  field_type_matching: %{
    Money.Ecto.Type => :string,
    MyReward.Avatar.Type => :file,
    },
  logo_mini: "My<b>R</b>",
  logo_full: "My<b>Rewards</b>",
  title: "My Rewards"

config :guardian, Guardian,
  allowed_algos: ["HS512"], # optional
  verify_module: Guardian.JWT,  # optional
  issuer: "MyRewards",
  ttl: {30, :days},
  allowed_drift: 2000,
  verify_issuer: true, # optional
  secret_key: "<REMOVED>",
  serializer: MyRewardsWeb.GuardianSerializer

config :money ,
  default_currency: :USD,
  separator: ",",
  delimeter: ".",
  symbol: false,
  symbol_on_right: false,
  symbol_space: false

config :xain, :after_callback, {Phoenix.HTML, :raw}



# %% Coherence Configuration %%   Don't remove this line
config :coherence,
  user_schema: MyRewards.User,
  repo: MyRewards.Repo,
  module: MyRewardsWeb,
  #changeset: {MyRewards.User, :coherence_registration},
  logged_out_url: "/",
  email_from_name: "EXAMPLE APP",
  email_from_email: "no-reply@example.com",
  opts: [:authenticatable, :recoverable, :lockable, :trackable, :unlockable_with_token, :registerable]

config :coherence, MyRewardsWeb.Coherence.Mailer,
  adapter: Swoosh.Adapters.Sendgrid,
  api_key: "<REMOVED>"
# %% End Coherence Configuration %%

# Import environment specific config. This must remain at the bottom
# of this file so it overrides the configuration defined above.
import_config "#{Mix.env}.exs"

```

**Comment by cdesch** [comment]
I tried switching version of elixir `1.4.2`--> `1.3.4`. No effect.

**Comment by smpallen99** [comment]
Sorry, I should have said `action` instead of `path`. Here is your issue: `<form accept-charset="UTF-8" action="/api/sessions" method="post"><input name="_csrf_token"...`.  The action is pointing to `/api/sessions`, but should have `/sessions`. 

Take a look at your `web/templates/coherence/session/new.html.eex` template and debug the session_path call.

**Comment by cdesch** [comment]
That was it. So obvious. Geez. Thank you. It got butchered in a refactoring session and slipped by code review. 

`web/views/coherence/coherence_view_helpers.ex` also got butchered. Fixed it. Thank you @smpallen99
