### ISSUE TITLE
:rememberable fails with UUID user ID

### ISSUE THREAD

**Issue by jaimeiniesta** [smpallen99/coherence#213]
Hello, I'm trying to enable the `:rememberable` option but I get an error. This is the migration I'm adding:

```elixir
  def change do
    create table(:rememberables) do
      add :series_hash, :string
      add :token_hash, :string
      add :token_created_at, :datetime
      add :user_id, references(:users, type: :uuid, on_delete: :delete_all)

      timestamps
    end
    create index(:rememberables, [:user_id])
    create index(:rememberables, [:series_hash])
    create index(:rememberables, [:token_hash])
    create unique_index(:rememberables, [:user_id, :series_hash, :token_hash])

    alter table(:users) do
      add :remember_created_at, :datetime
    end
  end
```

Note that I changed the `:user_id` to be of type UUID, and also added `:remember_created_at` to the `users` table as that was required.

I've added the `:rememberable` option to the config file, but now when I try to log in I get this error:

```
Request: POST /sessions
** (exit) an exception was raised:
    ** (Ecto.InvalidChangesetError) could not perform insert because changeset is invalid.

* Changeset changes

%{series_hash: "OFGni2FkoFvIkgrJh-XYaQ_oZw4=", token_created_at: #<DateTime(2017-06-04T22:21:27Z)>, token_hash: "UwDlvTb-7-Uz-MMZqxuPfAXaQ3s="}

* Changeset params

%{"series_hash" => "OFGni2FkoFvIkgrJh-XYaQ_oZw4=", "token_created_at" => #<DateTime(2017-06-04T22:21:27Z)>, "token_hash" => "UwDlvTb-7-Uz-MMZqxuPfAXaQ3s=", "user_id" => "9e66d442-de80-4473-acf8-6e735f4b30c8"}

* Changeset errors

[user_id: {"is invalid", [type: :id]}]

        (ecto) lib/ecto/repo/schema.ex:127: Ecto.Repo.Schema.insert!/4
        (coherence) web/controllers/session_controller.ex:254: Coherence.SessionController.save_rememberable/3
        (coherence) web/controllers/session_controller.ex:84: Coherence.SessionController.create/2
        (coherence) web/controllers/session_controller.ex:1: Coherence.SessionController.action/2
        (coherence) web/controllers/session_controller.ex:1: Coherence.SessionController.phoenix_controller_pipeline/2
        (MyApp) lib/MyApp/endpoint.ex:1: MyApp.Endpoint.instrument/4
        (MyApp) lib/phoenix/router.ex:261: MyApp.Router.dispatch/2
        (MyApp) web/router.ex:1: MyApp.Router.do_call/2
        (MyApp) lib/MyApp/endpoint.ex:1: MyApp.Endpoint.phoenix_pipeline/1
        (MyApp) lib/plug/debugger.ex:123: MyApp.Endpoint."call (overridable 3)"/2
        (MyApp) lib/MyApp/endpoint.ex:1: MyApp.Endpoint.call/2
        (plug) lib/plug/adapters/cowboy/handler.ex:15: Plug.Adapters.Cowboy.Handler.upgrade/4
        (cowboy) src/cowboy_protocol.erl:442: :cowboy_protocol.execute/4
```

Is that due to the user ID being an UUID? How can I set this up?

Thanks!

**Comment by veverkap** [comment]
FWIW, I'm getting the exact same issue.

**Comment by veverkap** [comment]
@smpallen99 I have created an example phoenix project at https://github.com/veverkap/jibber

When I try to login with the generic user, I get:

```
Ecto.InvalidChangesetError at POST /sessions
could not perform insert because changeset is invalid.
Applied changes
    %{series_hash: "FLgjPJjbqcyALnyvovvOOR0KWw4=",
      token_created_at: #<DateTime(2017-07-28T04:01:00.654815Z Etc/UTC)>,
      token_hash: "faU8HgzsPkwmoSAmUIlk-n1f0SE="}
Params
    %{"series_hash" => "FLgjPJjbqcyALnyvovvOOR0KWw4=",
      "token_created_at" => #<DateTime(2017-07-28T04:01:00.654815Z Etc/UTC)>,
      "token_hash" => "faU8HgzsPkwmoSAmUIlk-n1f0SE=",
      "user_id" => "57fbd713-4587-4506-88b4-2eaa41ecda54"}
Errors
    %{user_id: [{"is invalid", [type: :id, validation: :cast]}]}
Changeset
    #Ecto.Changeset<action: :insert,
     changes: %{series_hash: "FLgjPJjbqcyALnyvovvOOR0KWw4=",
       token_created_at: #<DateTime(2017-07-28T04:01:00.654815Z Etc/UTC)>,
       token_hash: "faU8HgzsPkwmoSAmUIlk-n1f0SE="},
     errors: [user_id: {"is invalid", [type: :id, validation: :cast]}],
     data: #Coherence.Rememberable<>, valid?: false>
```

**Comment by smpallen99** [comment]
This has been fixed on master. Installer now respects the projects binary_id settings. Also, the Invitation, Rememberable, and Trackable schemas are now generated in the user's app, so the programmer has complete control over these schemas.
