### ISSUE TITLE
function nil.signed_in_successfully/0 is undefined or private

### ISSUE THREAD

**Issue by cdesch** [smpallen99/coherence#318]
receive this error on coherence `0.4.0` after login in the `endpoint.ex`:

      function nil.signed_in_successfully/0 is undefined or private

```


[error] #PID<0.1074.0> running MyRewardsWeb.Endpoint terminated
Server: localhost:4000 (http)
Request: POST /sessions
** (exit) an exception was raised:
    ** (UndefinedFunctionError) function nil.signed_in_successfully/0 is undefined or private
        nil.signed_in_successfully()
        (coherence) lib/coherence/controllers/session_controller.ex:123: Coherence.SessionController.do_lockable/4
        (coherence) lib/coherence/controllers/session_controller.ex:1: Coherence.SessionController.action/2
        (coherence) lib/coherence/controllers/session_controller.ex:1: Coherence.SessionController.phoenix_controller_pipeline/2
```

**Comment by cdesch** [comment]
This was an upgrade from `0.3.0` to `0.4.0`.

After the upgrade, I needed to add: `messages_backend: MyRewardsWeb.Coherence.Messages,` to the config.ex
